version: "3.8"

services:
  django:
    build: .
    container_name: django
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/user/src/aplikacija
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=root
    ports:
      - "5432:5432"

